### ISSUE TITLE
Pattern support for job definition

### ISSUE THREAD

**Issue by reimannf** [sapcc/swift-http-import#3]
Instead of specify all possible sources and targets for OS package repos, it would be beneficial if one would be able to specify variants in the job definition, which would be evaluated be `swift-http-import`. The naivest approach would be to calculate the permutations of the variants and iterate over.

Example configs:

```
jobs:
  - variants:
      - product:
          - "SLE-SERVER"
          - "SLE-SDK"
      - release:
          - "12"
          - "12-LTTS"
          - "12-SP1"
          - "12-SP2"
    source:  http://mirror/SUSE/Updates/$product/$release/x86_64/update/
    target:  repo/suse/Updates/$product/$release/x86_64/update/
```

or 

```
jobs:
  - variants:
      - product:
          - "SLE-SERVER"
          - "SLE-SDK"
      - release:
          - "12"
          - "12-SP1"
          - "12-SP2"
    source:  http://mirror/SUSE/Products/$product/$release/x86_64/product/
    target:  repo/suse/Products/$product/$release/x86_64/product/
```

or

```
jobs:
  - variants:
      - sub:
          - ""
          - "-backports"
          - "-security"
          - "-updates"
          - "-proposed"
      - release:
          - "xenial"
    source:  http://ftp.halifax.rwth-aachen.de/ubuntu/dists/$release$sub
    target:  repo/ubuntu/dists/$release$sub
```
